# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 631bb259d93541b20dfc11495b0badf87c01d92f5b10a50205cc42298b01e120a32b9bd1e717e47e3c793275970f791f93c9726adb3c9897de1bb6489e0e4fc8

test:
  secret_key_base: c89681fcfb3a786a7731384c7ed4747e602974abc103540a2367871ae53aebd31270fb637f69290b85b32ce121386f553a2f410f1d1d800237182d3a6688edaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
